### PR TITLE
Done design and functionality of Job apply form

### PR DESCRIPTION
**Pull request by sayali05**
## 📝 Description

Created routes in backend to POST job application in database and design the job apply form with functionality(dynamic-data is inserting into database) and responsive. 

## 🎉 Demos

Screenshot 2023-10-11 at 22 50 34

### CODE REVIEW

**Review by BrantalikP — CHANGES_REQUESTED** [review]
Hey @sayali05 that's a great start!, but please check the design compliance one more time. I noticed that there are some details that need to be tweaked a bit and responsivity is a bit off. No worries, the review looks worse than actually it is 🙏

I am aware that we are not aiming for perfection, but let's keep it a bit consistent at least :) 

**Design**:
Screenshot 2023-10-12 at 8 41 28

**Responsivity**
https://github.com/HackYourFuture-CPH/class-25-ironside/assets/48878547/a6af4050-549a-480b-a2dc-3296edad0d38

**Implementation**
applyform

**Comment by hamoudi-hamoudi** [comment]
Screenshot 2023-10-14 025351
Screenshot 2023-10-14 025439
Screenshot 2023-10-14 025503

**Comment by hamoudi-hamoudi** [comment]
https://github.com/HackYourFuture-CPH/class-25-ironside/assets/33804102/0f1aae46-d2ae-43f3-b89a-7a763c7acaf6

**Review by BrantalikP — APPROVED** [review]
Amazing Work! 👏

**Pull request merged**
